"""Init database

Revision ID: 0289847c44fd
Revises: ef36b1b873ee
Create Date: 2024-11-01 18:47:06.580376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0289847c44fd'
down_revision: Union[str, None] = 'ef36b1b873ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
