"""Init database

Revision ID: ef36b1b873ee
Revises: 66130a03f682
Create Date: 2024-11-01 12:04:45.917674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef36b1b873ee'
down_revision: Union[str, None] = '66130a03f682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_per_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_per_item', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
